# Юнит 1

In [2]:
import numpy as np


A = np.array([[2,10,-2], [3, 2, -2], [8, 14, -6]])

np.linalg.matrix_rank(A.T)

2

In [4]:
np.linalg.matrix_rank([[5, 1], [10,2]])

1

## Юнит 2

## Задание 2.9

In [8]:
A = np.array([[1, -5], [2, 1], [1, 1]])
b = np.reshape(np.array([1,2,2]), (3,1))
w = np.reshape(np.array([1,1]), (2,1))

#print(A, b, w)

b_ = A@w

e = b - b_
print(e)

[[ 5]
 [-1]
 [ 0]]


# Задание 2.11

In [12]:
A = np.array([[1, 2], [-3, 1], [1, 2], [1, -1]])
b = np.reshape(np.array([1,4,5,0]), (4,1))

In [13]:
G = A.T@A
print(G)

[[12  0]
 [ 0 10]]


In [14]:
G_inv = np.linalg.inv(G)
print(G_inv)

[[0.08333333 0.        ]
 [0.         0.1       ]]


In [15]:
b_ = A.T@b
print(b_)

[[-6]
 [16]]


In [17]:
w_ = G_inv@A.T@b
print(w_)

[[-0.5]
 [ 1.6]]


# Юнит 4

## Задание 4.7

In [13]:
v = np.array([5, 1, 2])
u = np.array([4, 2, 8])

A = np.array([v,u]).T
print(np.corrcoef(v, u))

[[1.         0.05241424]
 [0.05241424 1.        ]]
0.954923980420481


## Задание 4.8

In [27]:
x1 = np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])
x2 = np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1]) 
x3 = np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3]) 
A = np.array([x1, x2, x3])
print(A)

C = np.corrcoef(A)
print(C)

print(np.linalg.matrix_rank(C))

print('{:.7f}'.format(np.linalg.det(C)))

[[ 5.1  1.8  2.1 10.3 12.1 12.6]
 [10.2  3.7  4.1 20.5 24.2 24.1]
 [ 2.5  0.9  1.1  5.1  6.1  6.3]]
[[1.         0.99925473 0.99983661]
 [0.99925473 1.         0.99906626]
 [0.99983661 0.99906626 1.        ]]
3
0.0000005


# Юнит 6

## Задание 6.1

In [7]:
x_1 = 1
x_2 = 4

#x_new = np.array([[1], [4]])


w_hat = np.array(np.reshape([10.4, 8, 0.5, 3, 0.4, 0], (6,1)))

A = np.array([1, x_1, x_2, x_1**2, x_2**2, x_1*x_2])

y_pred = A@w_hat
 
print(y_pred)

[29.8]


## Задание 6.4

In [11]:
#y = np.array(np.reshape([3, 7, -5, 21], (4,1)))
y = np.array([3, 7, -5, 21])


x = np.array([1, 3, -2, 9])

A = np.array([[1, x[0], x[0]**2], [1, x[1], x[1]**2], [1, x[2], x[2]**2], [1, x[3], x[3]**2]])

w_hat = np.linalg.inv(A.T@A)@A.T@y

print(w_hat)

[ 0.11446013  2.46095638 -0.01608801]


# Юнит 7

## Задание 7.4

In [13]:
x_1 = np.array([5, 9, 4, 3, 5])
x_2 = np.array([15, 18, 18, 19, 19])
x_3 = np.array([7, 6, 7, 7, 7])
y = np.array([24, 22, 35, 33, 36])
alpha = 1

X = np.array([[1, 1, 1, 1, 1], x_1, x_2, x_3]).T

w_hat = np.linalg.inv(X.T@X + alpha*np.eye(4))@X.T@y

print(w_hat)

[-0.08523045 -1.70784126  1.91141216  0.7293992 ]
