# Юнит 3

In [6]:
import pandas as pd
import numpy as np

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})



## Задание 3.6

In [4]:
Hut_Paradise_DF['7.Demo duration'] = [10, 20, 30, 15, 5, 40, 20, 8, 20]

totla_show_time = (Hut_Paradise_DF['5.Demo two weeks']*Hut_Paradise_DF['7.Demo duration']).sum()
print(totla_show_time)

1348


## Задание 3.7

In [8]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

vw_lc = 2*v - 3*w
print(vw_lc)

[-3 14  3  4  2]


## Задание 3.8

In [9]:
print(np.dot(vw_lc,u))

0


# Юнит 5

In [ ]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

## Задание 5.1

In [4]:
inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income]).T
print(inc)

[[100 150  90]
 [220 200  80]
 [140 130 100]]


## Задание 5.2

In [5]:
cons = np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption]).T
print(cons)

[[ 50 100 100]
 [ 50  80  20]
 [ 60 140 140]]


## Задание 5.3

In [7]:
inc02 = inc * (1 - 0.13)
print(inc02)

[[ 87.  130.5  78.3]
 [191.4 174.   69.6]
 [121.8 113.1  87. ]]


## Задание 5.4

In [9]:
balance = inc02 - cons
print(balance)

[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


# Юнит 7

## Задание 7.1

In [12]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

print(np.dot(A,x))

print(x.reshape(5,1))

[26 30]
[[1]
 [2]
 [3]
 [4]
 [5]]


## Задание 7.2

In [16]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

print(np.dot(B, A))
print(np.dot(B, A)[0,3])

[[  2   9  11  14]
 [  8 -10 -14 -11]]
14


## Задание 7.3

In [23]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A = np.array([x, y, z])

print(A)
print(np.dot(A.T,A))

[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]]
[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [27]:
import pandas as pd

Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

## Задание 7.4

In [30]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
count_array = np.array(Count_DF)
price_array = np.array(Price_DF)

print(count_array)

income = np.dot(count_array * price_array, com.reshape(5,1))
print(income)

[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]
[[11.3 ]
 [15.22]
 [11.9 ]
 [20.6 ]
 [41.9 ]
 [21.2 ]
 [11.49]
 [38.25]]


## Задание 7.5

In [35]:
income_workers = np.dot(count_array * price_array, np.reshape(np.ones((1,5)) - com, (5,1)))
print(income_workers)

[[ 50.2 ]
 [ 74.88]
 [ 59.1 ]
 [ 67.8 ]
 [166.6 ]
 [113.8 ]
 [ 66.21]
 [157.75]]


# Юнит 10

In [1]:
import numpy as np

## Задание 10.1

In [2]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

print(np.linalg.inv(A))

[[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]


## Задание 10.2

In [5]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

B = np.array([v1, v2, v3, v4]).T
print(B)

print(np.linalg.matrix_rank(B))

[[ 9  2  4  3]
 [10  0  0 -4]
 [ 7  5  0  3]
 [ 7  1  4 -1]
 [ 9  4  1 -4]]
4


## Задание 10.4

In [6]:
G = B.T@B
print(G)

[[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]


## Задание 10.5

In [7]:
print(np.linalg.det(G))

3716647.9999999995


## Задание 10.7

In [8]:
print(np.linalg.inv(G))

[[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
